version: '3.8'

services:
  relay:
    build:
      context: .
      dockerfile: Dockerfile.prod
    #container_name: wot-relay
    restart: unless-stopped
    ports:
      - "3334:3334"
    env_file:
      - .env
    
    volumes:
      - "./db:/app/db"
      - "./templates/index.html:${INDEX_PATH}"
      - "./templates/static:${STATIC_PATH}"
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3334/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    labels:
      - "autoheal=true"
    
    networks:
      - wot-network

  # Optional: Nginx reverse proxy for SSL termination
  nginx:
    image: nginx:alpine
    #container_name: wot-relay-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - relay
    labels:
      - "autoheal=true"
    networks:
      - wot-network
    profiles:
     - with-nginx


  # Autoheal for health monitoring and restarting unhealthy containers
  autoheal:
    image: willfarrell/autoheal:latest
    #container_name: wot-relay-autoheal
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
      - AUTOHEAL_INTERVAL=${AUTOHEAL_INTERVAL:-5}
      - AUTOHEAL_START_PERIOD=${AUTOHEAL_START_PERIOD:-0}
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=${AUTOHEAL_DEFAULT_STOP_TIMEOUT:-10}
    labels:
      - "autoheal=false"
    networks:
      - wot-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Tor proxy for anonymous access
  tor:
    image: dperson/torproxy
    #container_name: wot-relay-tor
    volumes:
      - ../tor-data:/var/lib/tor
    command: >
      -s "80;relay:3334"
    restart: unless-stopped
    mem_limit: 3.5g
    memswap_limit: 4g
    labels:
      - "autoheal=true"
    networks:
      - wot-network

networks:
  wot-network:
    driver: bridge
